import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";
import "./globals.css";
import LogOut from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {session && (
          <div>
            CURRENTLY LOGGED IN <br />
            <LogOut />
          </div>
        )}
        {!session && (
          <div>
            YOU ARE LOGGED OUT <br />
            <Link href={"/admin/login"}>LOGIN HERE</Link>
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
